Error while running StrainTool:
-------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/xanthos/Software/StrainTool/bin/./StrainTensor.py", line 511, in <module>
    compute__(grd, sta_list_utm, lcm, fout, fstats, vprint, **dargs)
  File "/home/xanthos/Software/StrainTool/bin/./StrainTensor.py", line 132, in compute__
    sstr.estimate()
  File "/usr/local/lib/python3.12/site-packages/pystrain-1.0.post1-py3.12.egg/pystrain/strain.py", line 988, in estimate
  File "/usr/local/lib/python3.12/site-packages/pystrain-1.0.post1-py3.12.egg/pystrain/strain.py", line 324, in ls_matrices
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.

Bug Fix:
------------------------------------------------------------------------------
The problem was that the Weight matrix computed via ShenStrain::make_weight_matrix() 
was a 2DIM matrix (of size Nx1), which did not allow setting the A columns in 
ShenStrain::ls_matrices() via the line "A[i]   = [ Wx*j for j in [1e0, 0e0,  dx, dy, 0e0, dy] ]". 
The fix was to flatten out the weight matrix returned by ShenStrain::make_weight_matrix().
